# .travis.yml for tmap.
language: r

r:
  - release

sudo: required

cache: packages

apt_packages:
  - r-cran-rgdal
  - libproj-dev

before_install:
  - cd $TRAVIS_BUILD_DIR
  - cd pkg
  
r_packages:
  - rgdal
  - rgeos
  - roxygen2
  - knitr
  - rmarkdown

r_github_packages: 
  - jimhester/covr

after_success:
  - R -e 'covr::codecov()'
