language: r
cache: packages

before_install:
  - sudo apt-get install libgdal-dev
  - sudo apt-get install libproj-dev
  - sudo apt-get install libgeos-dev
  - cd $TRAVIS_BUILD_DIR
  - cd pkg

sudo: required

warnings_are_errors: true

r_packages:
  - rgdal
  - rgeos
  - roxygen2
  - knitr
  - rmarkdown

r_github_packages: 
  - jimhester/covr

after_success:
  - R -e 'covr::codecov()'
