language: r
sudo: required
warnings_are_errors: false # for production this should be changed...

r_packages:
  - rmarkdown

env:
 global:
   - CRAN: http://cran.rstudio.com
   
before_install: cd pkg

notifications:
  email:
    on_success: change
    on_failure: change
