language: r
sudo: required
warnings_are_errors: false # for production this should be changed...

r_packages:
  - rmarkdown

env:
 global:
   - CRAN: http://cran.rstudio.com
 
apt_packages:
 - r-cran-rjava
 - gdal-bin 
 - libgdal1 

before_install: 
cd pkg
sudo apt-get download -y libgdal-dev
sudo dpkg-deb -x libgdal-dev*.deb /
sudo ln -sf /usr/lib/libgdal.so.1 /usr/lib/libgdal.so
sudo ldconfig

notifications:
  email:
    on_success: change
    on_failure: change
